[package]
name = "genkey"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.10", features = ["tokio"] }
rsa = "0.8"
rand = "0.8"
num_cpus = "1.13"
crossbeam = "0.8"
tokio = { version = "1", features = ["full"] }
async-std = "1.9"
